export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_ACTIVE: "USER_NOT_ACTIVE",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_OTP: "INVALID_OTP",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  OTP_EXPIRED: "OTP_EXPIRED",
  TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  USER_BANNED: "USER_BANNED",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  FAILED_TO_SEND_OTP: "FAILED_TO_SEND_OTP",
  REFRESH_TOKEN_REVOKED: "REFRESH_TOKEN_REVOKED",
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
