export const BannerMessage = {
  BANNER_NOT_FOUND: "Error.BannerNotFound",
  BANNER_TITLE_REQUIRED: "Error.BannerTitleRequired",
  BANNER_TITLE_TOO_LONG: "Error.BannerTitleTooLong",
  BANNER_IMAGE_URL_TOO_LONG: "Error.BannerImageUrlTooLong",
  BANNER_LINK_URL_TOO_LONG: "Error.BannerLinkUrlTooLong",
  BANNER_INVALID_DATE_RANGE: "Error.BannerInvalidDateRange",
  BANNER_INVALID_POSITION: "Error.BannerInvalidPosition",
  BANNER_POSITION_TAKEN: "Error.BannerPositionTaken",
  FAILED_TO_LOAD_BANNERS: "Error.FailedToLoadBanners",
  FAILED_TO_LOAD_BANNER_DETAIL: "Error.FailedToLoadBannerDetail",
  FAILED_TO_CREATE_BANNER: "Error.FailedToCreateBanner",
  FAILED_TO_UPDATE_BANNER: "Error.FailedToUpdateBanner",
  FAILED_TO_DELETE_BANNER: "Error.FailedToDeleteBanner",
  FAILED_TO_RESTORE_BANNER: "Error.FailedToRestoreBanner",
  BANNER_IMAGE_REQUIRED: "Error.BannerImageRequired",
  BANNER_IMAGE_INVALID_TYPE: "Error.BannerImageInvalidType",
  BANNER_IMAGE_TOO_LARGE: "Error.BannerImageTooLarge",
  FAILED_TO_UPLOAD_BANNER_IMAGE: "Error.FailedToUploadBannerImage",
  BANNER_IMAGE_NOT_FOUND: "Error.BannerImageNotFound",
} as const;
