export const ManageProposalMessage = {
  COVER_LETTER_REQUIRED: 'Error.ProposalCoverLetterRequired',
  COVER_LETTER_TOO_LONG: 'Error.ProposalCoverLetterTooLong',
  BID_AMOUNT_REQUIRED: 'Error.ProposalBidAmountRequired',
  BID_AMOUNT_POSITIVE: 'Error.ProposalBidAmountMustBePositive',
  DELIVERY_DAYS_REQUIRED: 'Error.ProposalDeliveryDaysRequired',
  DELIVERY_DAYS_POSITIVE: 'Error.ProposalDeliveryDaysMustBePositive',
  DRAFT_CONTENT_REQUIRED: 'Error.ProposalDraftContentRequired',
  PROPOSAL_NOT_FOUND: 'Error.ProposalNotFound',
  PROPOSAL_NOT_DRAFT: 'Error.ProposalNotDraft',
  PROPOSAL_INCOMPLETE: 'Error.ProposalIncomplete',
  JOB_NOT_FOUND: 'Error.ProposalJobNotFound',
  JOB_UNAVAILABLE: 'Error.ProposalJobUnavailable',
  JOB_EXPIRED: 'Error.ProposalJobExpired',
  CANNOT_PROPOSE_OWN_JOB: 'Error.CannotProposeOwnJob',
  ACTIVE_PROPOSAL_EXISTS: 'Error.ActiveProposalAlreadyExists',
  FREELANCER_ONLY: 'Error.ProposalFreelancerOnly',
  FORBIDDEN: 'Error.ProposalForbidden',
  FAILED_TO_CREATE: 'Error.FailedToCreateProposal',
  FAILED_TO_UPDATE: 'Error.FailedToUpdateProposal',
} as const;
